name: Release md CV

on:
  workflow_run:
    workflows: ["Release web CV"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release-cv-s2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get latest tag
        id: vars
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Set name as env
        run: echo "NAME=$(grep fullName resume.yaml | awk -F ':' '{print $2}' | tr -d '"' | sed 's/ //')" >> $GITHUB_ENV

      - name: Install exiftool, pandoc, wkhtmltopdf
        run: sudo apt update && sudo apt install -y pandoc wkhtmltopdf libimage-exiftool-perl

      - name: Run fix render script
        run: |
          python scripts/resume_fix_render.py

      - name: Convert to html
        run: |
          pandoc "resume_fixed.md" -t html -f markdown+hard_line_breaks -c "assets/css/normalize.css" --embed-resources --standalone -o "resume.html"

      - name: Run render commands
        run: |
          sed -i 's/<body[^>]*>/&<div class="pre-wrapper">/g' "resume.html"
          sed -i 's/<h3/<\/div><div class="entry"><h3/g' "resume.html"
          sed -i 's/<\/body>/<\/div><\/body>/g' "resume.html"

      - name: Convert to pdf
        run: |
          wkhtmltopdf --quiet --enable-local-file-access "resume.html" "resume.pdf"

      - name: Modify PDF metadata with exiftool
        run: |
          exiftool -Creator="$NAME" -Producer="$NAME" -Title="Resume - $NAME" -Author="$NAME" resume.pdf
          mv resume.pdf CV-S2-${{ steps.vars.outputs.TAG }}.pdf

      - name: Upload pdf to Release
        run: |
          gh release upload ${{ steps.vars.outputs.TAG }} CV-S2-${{ steps.vars.outputs.TAG }}.pdf --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
